service: chart-rec

# Options
# - region
# - stage
# Params
# - profile

frameworkVersion: ">=2.0.0 <4.0.0"

plugins:
  - serverless-s3-sync
  - serverless-cloudfront-invalidate

custom:
  s3Bucket: ${param:profile}-${opt:stage}
  s3Sync:
    - bucketName: ${self:custom.s3Bucket}
      localDir: build/
  cloudfrontInvalidate:
      - distributionIdKey: "CDNDistributionId"
        items:
          - "/*"

provider:
  stackName: ${param:profile}-${opt:stage} # Overwrite default CloudFormation stack name. Default is ${self:service}-${sls:stage}
  name: aws
  runtime: nodejs14.x
  profile: ${param:profile}
  region: ${opt:region}
  stage: ${opt:stage}
  environment:
    COGNITO_CLIENT_ID: "7vsffeornn2a2h5fsemsfp5efa"
    COGNITO_USER_POOL_ID: "ap-southeast-2_oLSeWN6PB"

resources:
  Description: ${param:profile} ${opt:stage}
  Resources:
    WebsiteS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    ## Specifying the policies to make sure all files inside the Bucket are available to CloudFront
    WebsiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebsiteS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.s3Bucket}/*
    ## Specifying the CloudFront Distribution to serve your Web Application
    WebsiteCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          HttpVersion: http2
          Origins:
            - DomainName: ${self:custom.s3Bucket}.s3.${opt:region}.amazonaws.com
              Id: ${self:custom.s3Bucket}.s3.${opt:region}.amazonaws.com
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          # Aliases:
          # - your-url.com
          DefaultRootObject: /index.html # Serve index by default since it is a SPA
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html # errors are handled by react router
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - HEAD
              - GET
            Compress: true
            DefaultTTL: 1800
            MinTTL: 0
            TargetOriginId: ${self:custom.s3Bucket}.s3.${opt:region}.amazonaws.com
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ViewerCertificate:
            CloudFrontDefaultCertificate: true

  Outputs:
    WebsiteCloudFrontDistribution:
      Description: Cloudfront site URL
      Value:
        "Fn::GetAtt": [WebsiteCloudFrontDistribution, DomainName]
    CDNDistributionId:
      Description: CDN distribution id.
      Value:
        Ref: WebsiteCloudFrontDistribution

